/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

import cjb.ci.*;
import datos.FerreteriaDAO;
import domain.Cliente;
import java.util.*;

/**
 *
 * @author Rafael
 */
public class VtnCosultaRFCliente extends javax.swing.JFrame {

    FerreteriaDAO ferrD = new FerreteriaDAO();

    /**
     * Creates new form VtnCosultaP
     */
    public VtnCosultaRFCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAmarillo = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        txtConsultaClv = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        panelBlanco = new javax.swing.JPanel();
        etqConsulta = new javax.swing.JLabel();
        etqPorCve = new javax.swing.JLabel();
        lbRFC = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        lbEscribeRFC = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        comoBoxRFC = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta por clave");
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAmarillo.setBackground(new java.awt.Color(255, 255, 204));
        panelAmarillo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtConsultaClv.setEditable(false);
        txtConsultaClv.setColumns(20);
        txtConsultaClv.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        txtConsultaClv.setRows(5);
        scrollPane.setViewportView(txtConsultaClv);

        panelAmarillo.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 451, 125));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("RFC:");
        panelAmarillo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, 30));

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqConsulta.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        etqConsulta.setText("Consulta");
        panelBlanco.add(etqConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 199, -1));

        etqPorCve.setFont(new java.awt.Font("Brush Script MT", 0, 24)); // NOI18N
        etqPorCve.setText("Por RFC");
        panelBlanco.add(etqPorCve, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        panelAmarillo.add(panelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 270, 70));

        lbRFC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbRFC.setForeground(new java.awt.Color(0, 0, 0));
        lbRFC.setText("RFC:");
        panelAmarillo.add(lbRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 184, -1, -1));

        txtRFC.setBackground(new java.awt.Color(255, 255, 255));
        txtRFC.setForeground(new java.awt.Color(0, 0, 0));
        txtRFC.setToolTipText("Escribe como inicia el RFC");
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRFCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCKeyTyped(evt);
            }
        });
        panelAmarillo.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 181, 172, -1));

        lbEscribeRFC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEscribeRFC.setForeground(new java.awt.Color(0, 0, 0));
        lbEscribeRFC.setText("Escribe como comienza el RFC");
        panelAmarillo.add(lbEscribeRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });
        panelAmarillo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        comoBoxRFC.setBackground(new java.awt.Color(255, 255, 153));
        comoBoxRFC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comoBoxRFC.setForeground(new java.awt.Color(0, 0, 0));
        comoBoxRFC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el RFC" }));
        comoBoxRFC.setToolTipText("Selecciona un producto");
        comoBoxRFC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comoBoxRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoBoxRFCActionPerformed(evt);
            }
        });
        panelAmarillo.add(comoBoxRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        getContentPane().add(panelAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        try {
            llenaComboCve();
        } catch (Exception e) {
            Mensaje.error(this, "Aún no hay registros");
            dispose();
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            comoBoxRFC.removeAllItems();
            this.comoBoxRFC.addItem("Selecciona el RFC");
            List<String> listRFC = this.ferrD.listaClienteLikeRFC(this.txtRFC.getText().toUpperCase());
            for (String rfc : listRFC) {
                this.comoBoxRFC.addItem(rfc);
            }
            this.comoBoxRFC.setVisible(true);
        } catch (Exception e) {
            this.comoBoxRFC.addItem("Selecciona el RFC");
            List<String> listRFC = this.ferrD.listaClienteLikeRFC(this.txtRFC.getText().toUpperCase());
            for (String rfc : listRFC) {
                this.comoBoxRFC.addItem(rfc);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtRFCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyPressed
        String s = "";
        if (evt.getKeyChar() == '\n') {
            Validaciones.enter(this, evt, this.btnBuscar);
            CtrlInterfaz.habilita(true, btnBuscar);
        }
    }//GEN-LAST:event_txtRFCKeyPressed

    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyTyped
        Validaciones.validaAlfanumerico(evt, 13, txtRFC.getText());
    }//GEN-LAST:event_txtRFCKeyTyped

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void comoBoxRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comoBoxRFCActionPerformed
        if (this.comoBoxRFC.getSelectedIndex() != 0) {
            String rfc = String.valueOf(this.comoBoxRFC.getSelectedItem());
            Cliente c = this.ferrD.listaClienteWhereRFC(rfc);
            String desp = c.toString();
            this.txtConsultaClv.setText(desp);
        } else {
            this.txtConsultaClv.setText("");
        }
    }//GEN-LAST:event_comoBoxRFCActionPerformed

    public void llenaComboCve() {
        List<String> arr = ferrD.listaRFCliente();
        for (String rfc : arr) {
            this.comoBoxRFC.addItem(rfc);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaRFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaRFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaRFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaRFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnCosultaRFCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> comoBoxRFC;
    private javax.swing.JLabel etqConsulta;
    private javax.swing.JLabel etqPorCve;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbEscribeRFC;
    private javax.swing.JLabel lbRFC;
    private javax.swing.JPanel panelAmarillo;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea txtConsultaClv;
    private javax.swing.JTextField txtRFC;
    // End of variables declaration//GEN-END:variables
}
