/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

import cjb.ci.*;
import datos.FerreteriaDAO;
import domain.Cliente;
import java.util.*;

/**
 *
 * @author Rafael
 */
public class VtnCosultaRCliente extends javax.swing.JFrame {

    FerreteriaDAO ferrD = new FerreteriaDAO();

    /**
     * Creates new form VtnCosultaP
     */
    public VtnCosultaRCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBusqueda = new javax.swing.ButtonGroup();
        panelAmarillo = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        txtConsultaClv = new javax.swing.JTextArea();
        panelBlanco = new javax.swing.JPanel();
        etqConsulta = new javax.swing.JLabel();
        etqPorCve = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lbEscribeRFC = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        comoBoxRC = new javax.swing.JComboBox<>();
        txtRFC = new javax.swing.JTextField();
        rbRFC = new javax.swing.JRadioButton();
        rbCorreo = new javax.swing.JRadioButton();
        madera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta por RFC/Correo del cliente");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAmarillo.setBackground(new java.awt.Color(255, 255, 204));
        panelAmarillo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtConsultaClv.setEditable(false);
        txtConsultaClv.setColumns(20);
        txtConsultaClv.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        txtConsultaClv.setRows(5);
        scrollPane.setViewportView(txtConsultaClv);

        panelAmarillo.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 451, 125));

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqConsulta.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        etqConsulta.setForeground(new java.awt.Color(0, 0, 0));
        etqConsulta.setText("Consulta");
        panelBlanco.add(etqConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 199, -1));

        etqPorCve.setFont(new java.awt.Font("Brush Script MT", 0, 24)); // NOI18N
        etqPorCve.setForeground(new java.awt.Color(0, 0, 0));
        etqPorCve.setText("Por RFC-Correo");
        panelBlanco.add(etqPorCve, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        panelAmarillo.add(panelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 560, 70));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setToolTipText("Escribe como inicia el Correo");
        txtCorreo.setEnabled(false);
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        panelAmarillo.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 172, -1));

        lbEscribeRFC.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbEscribeRFC.setForeground(new java.awt.Color(255, 255, 255));
        lbEscribeRFC.setText("Escribe como comienza el RFC o el Correo");
        panelAmarillo.add(lbEscribeRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });
        panelAmarillo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        comoBoxRC.setBackground(new java.awt.Color(255, 255, 255));
        comoBoxRC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comoBoxRC.setForeground(new java.awt.Color(0, 0, 0));
        comoBoxRC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona..." }));
        comoBoxRC.setToolTipText("Selecciona un producto");
        comoBoxRC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comoBoxRC.setEnabled(false);
        comoBoxRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoBoxRCActionPerformed(evt);
            }
        });
        panelAmarillo.add(comoBoxRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        txtRFC.setBackground(new java.awt.Color(255, 255, 255));
        txtRFC.setForeground(new java.awt.Color(0, 0, 0));
        txtRFC.setToolTipText("Escribe como inicia el RFC");
        txtRFC.setEnabled(false);
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRFCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCKeyTyped(evt);
            }
        });
        panelAmarillo.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 172, -1));

        bgBusqueda.add(rbRFC);
        rbRFC.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rbRFC.setForeground(new java.awt.Color(255, 255, 255));
        rbRFC.setText("RFC");
        rbRFC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRFCActionPerformed(evt);
            }
        });
        panelAmarillo.add(rbRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        bgBusqueda.add(rbCorreo);
        rbCorreo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rbCorreo.setForeground(new java.awt.Color(255, 255, 255));
        rbCorreo.setText("Correo");
        rbCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCorreoActionPerformed(evt);
            }
        });
        panelAmarillo.add(rbCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        madera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maderaOscura2.jpg"))); // NOI18N
        panelAmarillo.add(madera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 560, 450));

        getContentPane().add(panelAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            if (this.rbRFC.isSelected()) {
                comoBoxRC.removeAllItems();
                this.comoBoxRC.addItem("Selecciona el RFC");
                List<String> listRFC = this.ferrD.listaClienteLikeRFC(this.txtRFC.getText());
                for (String rfc : listRFC) {
                    this.comoBoxRC.addItem(rfc);
                }
                CtrlInterfaz.habilita(true, this.comoBoxRC);
            } else if (this.rbCorreo.isSelected()) {
                comoBoxRC.removeAllItems();
                this.comoBoxRC.addItem("Selecciona el correo");
                List<String> listCorreo = this.ferrD.listaClienteLikeCorreo(this.txtCorreo.getText());
                for (String rfc : listCorreo) {
                    this.comoBoxRC.addItem(rfc);
                }
                CtrlInterfaz.habilita(true, this.comoBoxRC);
            } else {
                CtrlInterfaz.habilita(false, this.btnBuscar);
            }
        } catch (Exception e) {
            if (this.rbRFC.isSelected()) {
                this.comoBoxRC.addItem("Selecciona el RFC");
                List<String> listRFC = this.ferrD.listaClienteLikeRFC(this.txtRFC.getText());
                for (String rfc : listRFC) {
                    this.comoBoxRC.addItem(rfc);
                }
                CtrlInterfaz.habilita(true, this.comoBoxRC);
            } else if (this.rbCorreo.isSelected()) {
                this.comoBoxRC.addItem("Selecciona el correo");
                List<String> listCorreo = this.ferrD.listaClienteLikeCorreo(this.txtCorreo.getText());
                for (String rfc : listCorreo) {
                    this.comoBoxRC.addItem(rfc);
                }
                CtrlInterfaz.habilita(true, this.comoBoxRC);
            } else {
                CtrlInterfaz.habilita(false, this.btnBuscar);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        String s = "";
        if (evt.getKeyChar() == '\n') {
            Validaciones.enter(this, evt, this.btnBuscar);
            CtrlInterfaz.habilita(true, btnBuscar);
        }
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        if (txtCorreo.getText().length() >= 38) {
            Mensaje.error(this, "El tiene demasiados caracteres, verifique.");
            CtrlInterfaz.limpia(txtCorreo);
            CtrlInterfaz.cambia(this.txtCorreo);
        }
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void comoBoxRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comoBoxRCActionPerformed
        if (this.comoBoxRC.getSelectedIndex() != 0) {
            String s;
            if (this.rbRFC.isSelected()) {
                s = String.valueOf(this.comoBoxRC.getSelectedItem());
                Cliente c = this.ferrD.listaClienteWhereRFC(s);
                String desp = c.toString();
                this.txtConsultaClv.setText(desp);
            } else {
                s = String.valueOf(this.comoBoxRC.getSelectedItem());
                Cliente c = this.ferrD.listaClienteWhereCorreo(s);
                String desp = c.toString();
                this.txtConsultaClv.setText(desp);
            }
        } else {
            this.txtConsultaClv.setText("");
        }
    }//GEN-LAST:event_comoBoxRCActionPerformed

    private void txtRFCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyPressed
        String s = "";
        if (evt.getKeyChar() == '\n') {
            Validaciones.enter(this, evt, this.btnBuscar);
            CtrlInterfaz.habilita(true, btnBuscar);
        }
    }//GEN-LAST:event_txtRFCKeyPressed

    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyTyped
        Validaciones.validaAlfanumerico(evt, 13, txtRFC.getText());
    }//GEN-LAST:event_txtRFCKeyTyped

    private void rbRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRFCActionPerformed
        try {
            if (rbRFC.isSelected()) {
                CtrlInterfaz.limpia(this.txtCorreo);
                comoBoxRC.removeAllItems();
                this.comoBoxRC.addItem("Selecciona...");
                rbRFC.setSelected(rootPaneCheckingEnabled);
                CtrlInterfaz.habilita(true, txtRFC);
                CtrlInterfaz.cambia(txtRFC);
                CtrlInterfaz.habilita(false, comoBoxRC, txtCorreo, btnBuscar);
            } else {
                CtrlInterfaz.habilita(false, txtRFC, txtCorreo, btnBuscar);
            }
        } catch (Exception e) {
            this.comoBoxRC.addItem("Selecciona...");
            rbRFC.setSelected(rootPaneCheckingEnabled);
            CtrlInterfaz.habilita(true, txtRFC);
            CtrlInterfaz.habilita(false, comoBoxRC, txtCorreo, btnBuscar);
        }

    }//GEN-LAST:event_rbRFCActionPerformed

    private void rbCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCorreoActionPerformed
        try {
            if (rbCorreo.isSelected()) {
                CtrlInterfaz.limpia(this.txtRFC);
                comoBoxRC.removeAllItems();
                this.comoBoxRC.addItem("Selecciona...");
                rbCorreo.setSelected(rootPaneCheckingEnabled);
                CtrlInterfaz.habilita(true, txtCorreo);
                CtrlInterfaz.cambia(txtCorreo);
                CtrlInterfaz.habilita(false, comoBoxRC, txtRFC, btnBuscar);
            } else {
                CtrlInterfaz.habilita(false, txtRFC, txtCorreo, btnBuscar);
            }
        } catch (Exception e) {
            this.comoBoxRC.addItem("Selecciona...");
            rbCorreo.setSelected(rootPaneCheckingEnabled);
            CtrlInterfaz.habilita(true, txtCorreo);
            CtrlInterfaz.habilita(false, comoBoxRC, txtRFC, btnBuscar);
        }
    }//GEN-LAST:event_rbCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaRCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaRCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaRCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaRCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnCosultaRCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgBusqueda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> comoBoxRC;
    private javax.swing.JLabel etqConsulta;
    private javax.swing.JLabel etqPorCve;
    private javax.swing.JLabel lbEscribeRFC;
    private javax.swing.JLabel madera;
    private javax.swing.JPanel panelAmarillo;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JRadioButton rbCorreo;
    private javax.swing.JRadioButton rbRFC;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea txtConsultaClv;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtRFC;
    // End of variables declaration//GEN-END:variables
}
