/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

import cjb.ci.Mensaje;
import datos.FerreteriaDAO;
import domain.Productos;
import java.util.*;

/**
 *
 * @author Rafael
 */
public class VtnCosultaCveP extends javax.swing.JFrame {

    FerreteriaDAO ferrD = new FerreteriaDAO();

    /**
     * Creates new form VtnCosultaP
     */
    public VtnCosultaCveP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etqConsulta = new javax.swing.JLabel();
        panelBlanco = new javax.swing.JPanel();
        etqPorCve = new javax.swing.JLabel();
        panelAmarillo = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        txtConsultaClv = new javax.swing.JTextArea();
        comoBoxProd = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        madera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta por clave");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqConsulta.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        etqConsulta.setForeground(new java.awt.Color(0, 0, 0));
        etqConsulta.setText("Consulta");
        getContentPane().add(etqConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 199, -1));

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqPorCve.setFont(new java.awt.Font("Brush Script MT", 0, 24)); // NOI18N
        etqPorCve.setForeground(new java.awt.Color(0, 0, 0));
        etqPorCve.setText("Por clave");
        panelBlanco.add(etqPorCve, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        getContentPane().add(panelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 60));

        panelAmarillo.setBackground(new java.awt.Color(255, 255, 204));
        panelAmarillo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtConsultaClv.setEditable(false);
        txtConsultaClv.setColumns(20);
        txtConsultaClv.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        txtConsultaClv.setRows(5);
        scrollPane.setViewportView(txtConsultaClv);

        panelAmarillo.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 169, 451, 125));

        comoBoxProd.setBackground(new java.awt.Color(255, 255, 255));
        comoBoxProd.setForeground(new java.awt.Color(0, 0, 0));
        comoBoxProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona clave de producto" }));
        comoBoxProd.setToolTipText("Selecciona un producto");
        comoBoxProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comoBoxProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoBoxProdActionPerformed(evt);
            }
        });
        panelAmarillo.add(comoBoxProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 190, -1));

        jPanel1.setBackground(new java.awt.Color(0, 26, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clave del producto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        panelAmarillo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 105, 360, 50));

        madera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maderaOscura.jpg"))); // NOI18N
        panelAmarillo.add(madera, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 690, 380));

        getContentPane().add(panelAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        try {
            llenaComboCve();
        } catch (Exception e) {
            Mensaje.error(this, "Aún no hay registros");
            dispose();
        }

    }//GEN-LAST:event_formWindowOpened

    private void comoBoxProdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comoBoxProdActionPerformed
    {//GEN-HEADEREND:event_comoBoxProdActionPerformed
        if (this.comoBoxProd.getSelectedIndex() != 0) {
            int idProducto = Integer.parseInt(String.valueOf(this.comoBoxProd.getSelectedItem()));
            Productos p = this.ferrD.listaPWhere(idProducto);
            String desp = p.toString();
            this.txtConsultaClv.setText(desp);
        } else {
            this.txtConsultaClv.setText("");
        }
    }//GEN-LAST:event_comoBoxProdActionPerformed

    public void llenaComboCve() {
        List<Integer> arr = ferrD.listaIdP();
        for (int idP : arr) {
            this.comoBoxProd.addItem(String.valueOf(idP));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaCveP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaCveP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaCveP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaCveP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnCosultaCveP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comoBoxProd;
    private javax.swing.JLabel etqConsulta;
    private javax.swing.JLabel etqPorCve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel madera;
    private javax.swing.JPanel panelAmarillo;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea txtConsultaClv;
    // End of variables declaration//GEN-END:variables
}
