/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;


/**
 *
 * @author Rafael
 */
public class VtnConsulVItem extends javax.swing.JFrame
{

    /**
     * Creates new form VtnProductosB
     */
    public VtnConsulVItem()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        txtBajasTitulo = new javax.swing.JLabel();
        btnClvB = new javax.swing.JButton();
        btnNomB = new javax.swing.JButton();
        btnNomB1 = new javax.swing.JButton();
        panelConsultas = new javax.swing.JPanel();
        panelSeleccion = new javax.swing.JPanel();
        txtSelB = new javax.swing.JLabel();
        maderaOscura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de ventas");
        setIconImage(getIconImage());
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(204, 204, 255));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBajasTitulo.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        txtBajasTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtBajasTitulo.setText("Consulta de ventas");
        panelFondo.add(txtBajasTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 23, -1, -1));

        btnClvB.setBackground(new java.awt.Color(255, 255, 255));
        btnClvB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClvB.setForeground(new java.awt.Color(0, 0, 0));
        btnClvB.setText("Factura");
        btnClvB.setToolTipText("Consulta tus facturas");
        btnClvB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClvB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClvBActionPerformed(evt);
            }
        });
        panelFondo.add(btnClvB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        btnNomB.setBackground(new java.awt.Color(255, 255, 255));
        btnNomB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNomB.setForeground(new java.awt.Color(0, 0, 0));
        btnNomB.setText("Nota");
        btnNomB.setToolTipText("Consulta tus notas");
        btnNomB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNomB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomBActionPerformed(evt);
            }
        });
        panelFondo.add(btnNomB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        btnNomB1.setBackground(new java.awt.Color(255, 255, 255));
        btnNomB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNomB1.setForeground(new java.awt.Color(0, 0, 0));
        btnNomB1.setText("Vendedor");
        btnNomB1.setToolTipText("Consulta tus facturas o notas por clave del vendedor");
        btnNomB1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNomB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomB1ActionPerformed(evt);
            }
        });
        panelFondo.add(btnNomB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        panelConsultas.setBackground(new java.awt.Color(255, 255, 255));
        panelConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 390, 50));

        panelSeleccion.setBackground(new java.awt.Color(0, 102, 153));

        txtSelB.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtSelB.setForeground(new java.awt.Color(255, 255, 255));
        txtSelB.setText("Selecciona tu tipo de consulta:");

        javax.swing.GroupLayout panelSeleccionLayout = new javax.swing.GroupLayout(panelSeleccion);
        panelSeleccion.setLayout(panelSeleccionLayout);
        panelSeleccionLayout.setHorizontalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSelB, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSeleccionLayout.setVerticalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtSelB)
                .addContainerGap())
        );

        panelFondo.add(panelSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 320, 50));

        maderaOscura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maderaOscura2.jpg"))); // NOI18N
        panelFondo.add(maderaOscura, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 610, 210));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClvBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClvBActionPerformed
    {//GEN-HEADEREND:event_btnClvBActionPerformed
        VtnDespFac vtnDespF = new VtnDespFac();
        vtnDespF.setVisible(true);
    }//GEN-LAST:event_btnClvBActionPerformed

    private void btnNomBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNomBActionPerformed
    {//GEN-HEADEREND:event_btnNomBActionPerformed
        VtnDespNot vtnDepNot = new VtnDespNot();
        vtnDepNot.setVisible(true);
    }//GEN-LAST:event_btnNomBActionPerformed

    private void btnNomB1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNomB1ActionPerformed
    {//GEN-HEADEREND:event_btnNomB1ActionPerformed
        VtnDespVendedor vtnDespV = new VtnDespVendedor();
        vtnDespV.setVisible(true);
    }//GEN-LAST:event_btnNomB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsulVItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsulVItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsulVItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsulVItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnConsulVItem().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClvB;
    private javax.swing.JButton btnNomB;
    private javax.swing.JButton btnNomB1;
    private javax.swing.JLabel maderaOscura;
    private javax.swing.JPanel panelConsultas;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JLabel txtBajasTitulo;
    private javax.swing.JLabel txtSelB;
    // End of variables declaration//GEN-END:variables
}
