/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

/**
 *
 * @author Rafael
 */
public class VtnConsulCItem extends javax.swing.JFrame {

    /**
     * Creates new form VtnProductosB
     */
    public VtnConsulCItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        btnNomB = new javax.swing.JButton();
        btnClvB = new javax.swing.JButton();
        panelConsultas = new javax.swing.JPanel();
        txtBajasTitulo = new javax.swing.JLabel();
        panelSeleccion = new javax.swing.JPanel();
        txtSelB = new javax.swing.JLabel();
        maderaOscura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de productos");
        setIconImage(getIconImage());
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(0, 153, 153));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNomB.setBackground(new java.awt.Color(255, 255, 255));
        btnNomB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNomB.setForeground(new java.awt.Color(0, 0, 0));
        btnNomB.setText("RFC del cliente");
        btnNomB.setToolTipText("Consulta algún producto por clave del producto");
        btnNomB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNomB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomBActionPerformed(evt);
            }
        });
        panelFondo.add(btnNomB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        btnClvB.setBackground(new java.awt.Color(255, 255, 255));
        btnClvB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClvB.setForeground(new java.awt.Color(0, 0, 0));
        btnClvB.setText("Todos los clientes");
        btnClvB.setToolTipText("Consulta todos tus productos");
        btnClvB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClvB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClvBActionPerformed(evt);
            }
        });
        panelFondo.add(btnClvB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        panelConsultas.setBackground(new java.awt.Color(255, 255, 255));
        panelConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBajasTitulo.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        txtBajasTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtBajasTitulo.setText("Consulta de clientes");
        panelConsultas.add(txtBajasTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 40));

        panelFondo.add(panelConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 450, 50));

        panelSeleccion.setBackground(new java.awt.Color(0, 102, 153));

        txtSelB.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtSelB.setForeground(new java.awt.Color(255, 255, 255));
        txtSelB.setText("Selecciona tu tipo de consulta:");

        javax.swing.GroupLayout panelSeleccionLayout = new javax.swing.GroupLayout(panelSeleccion);
        panelSeleccion.setLayout(panelSeleccionLayout);
        panelSeleccionLayout.setHorizontalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtSelB)
                .addGap(16, 16, 16))
        );
        panelSeleccionLayout.setVerticalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(txtSelB)
                .addContainerGap())
        );

        panelFondo.add(panelSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 340, 60));

        maderaOscura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/madera2.jpg"))); // NOI18N
        panelFondo.add(maderaOscura, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 550, 240));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClvBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClvBActionPerformed
    {//GEN-HEADEREND:event_btnClvBActionPerformed
        VtnCosultaCl vtnConsultaTodosCliente = new VtnCosultaCl();
        vtnConsultaTodosCliente.setVisible(true);
    }//GEN-LAST:event_btnClvBActionPerformed

    private void btnNomBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNomBActionPerformed
    {//GEN-HEADEREND:event_btnNomBActionPerformed
        VtnCosultaRFCliente vtnCosultaRFC = new VtnCosultaRFCliente();
        vtnCosultaRFC.setVisible(true);
    }//GEN-LAST:event_btnNomBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnConsulCItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnConsulCItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnConsulCItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnConsulCItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnConsulCItem().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClvB;
    private javax.swing.JButton btnNomB;
    private javax.swing.JLabel maderaOscura;
    private javax.swing.JPanel panelConsultas;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JLabel txtBajasTitulo;
    private javax.swing.JLabel txtSelB;
    // End of variables declaration//GEN-END:variables
}
