/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

import datos.*;
import cjb.ci.Mensaje;
import java.util.*;
import domain.Productos;

/**
 *
 * @author Rafael
 */
public class VtnCosultaP extends javax.swing.JFrame {

    /**
     * Creates new form VtnCosultaP
     */
    public VtnCosultaP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etqCons = new javax.swing.JLabel();
        etqTodP = new javax.swing.JLabel();
        panelBlanco = new javax.swing.JPanel();
        panelNaranja = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        txtConsultaP = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta todos los productos");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqCons.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        etqCons.setText("Consulta");
        getContentPane().add(etqCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 199, -1));

        etqTodP.setFont(new java.awt.Font("Brush Script MT", 0, 24)); // NOI18N
        etqTodP.setText("Todos los productos");
        getContentPane().add(etqTodP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelBlancoLayout = new javax.swing.GroupLayout(panelBlanco);
        panelBlanco.setLayout(panelBlancoLayout);
        panelBlancoLayout.setHorizontalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        panelBlancoLayout.setVerticalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        getContentPane().add(panelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 270, 60));

        panelNaranja.setBackground(new java.awt.Color(255, 220, 186));

        txtConsultaP.setEditable(false);
        txtConsultaP.setColumns(20);
        txtConsultaP.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        txtConsultaP.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaP.setRows(5);
        scrollPane.setViewportView(txtConsultaP);

        javax.swing.GroupLayout panelNaranjaLayout = new javax.swing.GroupLayout(panelNaranja);
        panelNaranja.setLayout(panelNaranjaLayout);
        panelNaranjaLayout.setHorizontalGroup(
            panelNaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNaranjaLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        panelNaranjaLayout.setVerticalGroup(
            panelNaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNaranjaLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(panelNaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        try {
            llena();
        } catch (Exception e) {
            Mensaje.error(this, "Aún no hay registros");
            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    public void llena() {

        String desp = muestraArea();
        this.txtConsultaP.setText(desp);
    }

    public static String muestraArea() {
        FerreteriaDAO ferrD = new FerreteriaDAO();
        List<Productos> listP = ferrD.listaP();
        String s = "ID\tNombre\t\tPrecio\t   Cantidad"
                + "\n--------------------------------------------\n";
        for (Productos p : listP) {

            String cve = "";
            String nom = "";
            String pre = "";

            int l1, l2, l3;
            l1 = 8 - (String.valueOf(p.getIdP()).length());
            l2 = 17 - (p.getNombre().length());
            l3 = 12 - (String.valueOf(p.getPrecio()).length());
            for (int i = 0; i < l1; i++) {
                cve += " ";
            }

            for (int i = 0; i < l2; i++) {

                nom += " ";
            }

            for (int i = 0; i < l3; i++) {
                pre += " ";
            }
            s += ((p.getIdP()) + (cve) + p.getNombre().toUpperCase() + (nom) + (p.getPrecio()) + (pre) + " " + (p.getCantidad()) + "\n");
        }
        return s;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnCosultaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnCosultaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etqCons;
    private javax.swing.JLabel etqTodP;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPanel panelNaranja;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea txtConsultaP;
    // End of variables declaration//GEN-END:variables
}
