/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

import cjb.ci.Mensaje;
import datos.FerreteriaDAO;
import domain.*;
import java.util.*;

/**
 *
 * @author Rafael
 */
public class VtnDespFac extends javax.swing.JFrame {

    FerreteriaDAO ferrD = new FerreteriaDAO();
    int IdFN;

    /**
     * Creates new form VtnDespFac
     */
    public VtnDespFac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAzul = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        comboBoxF = new javax.swing.JComboBox<>();
        scrollPane = new javax.swing.JScrollPane();
        txtConsultaF = new javax.swing.JTextArea();
        panelBlanco = new javax.swing.JPanel();
        etqF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de facturas");
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAzul.setBackground(new java.awt.Color(209, 255, 239));
        panelAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        txtTitulo.setText("Consulta tu factura");
        panelAzul.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 14, -1, -1));

        comboBoxF.setBackground(new java.awt.Color(204, 255, 204));
        comboBoxF.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona tu factura" }));
        comboBoxF.setToolTipText("Selecciona una factura");
        comboBoxF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboBoxF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFActionPerformed(evt);
            }
        });
        panelAzul.add(comboBoxF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 86, 160, 30));

        txtConsultaF.setEditable(false);
        txtConsultaF.setColumns(20);
        txtConsultaF.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        txtConsultaF.setRows(5);
        scrollPane.setViewportView(txtConsultaF);

        panelAzul.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 136, 436, 250));

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelBlancoLayout = new javax.swing.GroupLayout(panelBlanco);
        panelBlanco.setLayout(panelBlancoLayout);
        panelBlancoLayout.setHorizontalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        panelBlancoLayout.setVerticalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        panelAzul.add(panelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 70));

        etqF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etqF.setForeground(new java.awt.Color(0, 0, 0));
        etqF.setText("Factura: ");
        panelAzul.add(etqF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        getContentPane().add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        try {
            llenaCombo();
        } catch (Exception e) {
            Mensaje.error(this, "Aún no hay registros");
            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void comboBoxFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboBoxFActionPerformed
    {//GEN-HEADEREND:event_comboBoxFActionPerformed
        try {
            if (this.comboBoxF.getSelectedIndex() != 0) {
//                this.IdFN = Integer.parseInt(String.valueOf(comboBoxF.getSelectedItem()));
//                FacturaNota fn = this.ferrD.listaFacturaNotaWhere(IdFN);
//                Ventas v = this.ferrD.listaVentasWhere(this.IdFN);
//                String desp = fn.despFactura() + "\n------------------------------------\n" + v.toString();
//                txtConsultaF.setText(desp);
            } else {
                this.txtConsultaF.setText("");
            }
        } catch (Exception e) {
            //e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_comboBoxFActionPerformed

    public void llenaCombo() {
        List<Integer> arr = ferrD.listaFacNotIsNull();
        for (int idF : arr) {
            this.comboBoxF.addItem(String.valueOf(idF));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnDespFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnDespFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnDespFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnDespFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnDespFac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxF;
    private javax.swing.JLabel etqF;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea txtConsultaF;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
