/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

import cjb.ci.*;
import static datos.Conexion.*;
import datos.FerreteriaDAO;
import domain.*;
import java.sql.*;
import java.util.*;

/**
 *
 * @author Rafael
 */
public class VtnFactura extends javax.swing.JFrame {

    FerreteriaDAO ferrD = new FerreteriaDAO();
    int pos, prod_idP, vend_idV, cantidad, cantP, updateCant;
    double total;

    Connection conexion = getConnection();
    FerreteriaDAO ferrDaoT = new FerreteriaDAO(conexion);
    Productos prod;
    List<FacturaNota> fn = new ArrayList<>();

    /**
     * Creates new form VtnFactura
     */
    public VtnFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGis = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCancelarF = new javax.swing.JButton();
        etqCveVend = new javax.swing.JLabel();
        etqRfc = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        etqCantP = new javax.swing.JLabel();
        txtCantP = new javax.swing.JTextField();
        etqCantP1 = new javax.swing.JLabel();
        comboBoxProd = new javax.swing.JComboBox<>();
        btnConfirmarF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelBlanco = new javax.swing.JPanel();
        etqFactura = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAVta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDteVn = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        etqDetV = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        etqDetV1 = new javax.swing.JLabel();
        comboBoxVend = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Factura");
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGis.setBackground(new java.awt.Color(204, 204, 204));
        panelGis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(51, 153, 0));
        btnAgregar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregarKeyPressed(evt);
            }
        });
        panelGis.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        btnCancelarF.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarF.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCancelarF.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarF.setText("Cancelar");
        btnCancelarF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFActionPerformed(evt);
            }
        });
        panelGis.add(btnCancelarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        etqCveVend.setForeground(new java.awt.Color(0, 0, 0));
        etqCveVend.setText("Clave del vendedor: ");
        panelGis.add(etqCveVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        etqRfc.setForeground(new java.awt.Color(0, 0, 0));
        etqRfc.setText("RFC: ");
        panelGis.add(etqRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtRfc.setEnabled(false);
        txtRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcActionPerformed(evt);
            }
        });
        txtRfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRfcKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRfcKeyTyped(evt);
            }
        });
        panelGis.add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 168, -1));

        etqCantP.setForeground(new java.awt.Color(0, 0, 0));
        etqCantP.setText("Producto:");
        panelGis.add(etqCantP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        txtCantP.setEnabled(false);
        txtCantP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantPActionPerformed(evt);
            }
        });
        txtCantP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantPKeyTyped(evt);
            }
        });
        panelGis.add(txtCantP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 80, -1));

        etqCantP1.setForeground(new java.awt.Color(0, 0, 0));
        etqCantP1.setText("Cantidad:");
        panelGis.add(etqCantP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        comboBoxProd.setBackground(new java.awt.Color(204, 255, 255));
        comboBoxProd.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona tu producto" }));
        comboBoxProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboBoxProd.setEnabled(false);
        comboBoxProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboBoxProdMousePressed(evt);
            }
        });
        comboBoxProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProdActionPerformed(evt);
            }
        });
        panelGis.add(comboBoxProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, 20));

        btnConfirmarF.setBackground(new java.awt.Color(51, 153, 0));
        btnConfirmarF.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnConfirmarF.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarF.setText("Confirmar");
        btnConfirmarF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirmarF.setEnabled(false);
        btnConfirmarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarFActionPerformed(evt);
            }
        });
        btnConfirmarF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmarFKeyPressed(evt);
            }
        });
        panelGis.add(btnConfirmarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqFactura.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        etqFactura.setText("Factura");
        panelBlanco.add(etqFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 19, -1, 31));

        jPanel1.add(panelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -10, 210, 60));

        txtAVta.setEditable(false);
        txtAVta.setColumns(20);
        txtAVta.setRows(5);
        jScrollPane2.setViewportView(txtAVta);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 380, 210));

        txtDteVn.setEditable(false);
        txtDteVn.setColumns(20);
        txtDteVn.setRows(5);
        jScrollPane3.setViewportView(txtDteVn);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 340, 210));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        etqDetV.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        etqDetV.setForeground(new java.awt.Color(255, 255, 255));
        etqDetV.setText("Venta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(etqDetV)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqDetV)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 80, 50));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        etqDetV1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        etqDetV1.setForeground(new java.awt.Color(255, 255, 255));
        etqDetV1.setText("Detalle de venta:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqDetV1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqDetV1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 140, 50));

        comboBoxVend.setBackground(new java.awt.Color(255, 255, 153));
        comboBoxVend.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxVend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el vendedor" }));
        comboBoxVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVendActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, -1));

        panelGis.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1020, 380));

        getContentPane().add(panelGis, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -3, 1060, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRfcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtRfcActionPerformed
    {//GEN-HEADEREND:event_txtRfcActionPerformed

    }//GEN-LAST:event_txtRfcActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        try {
            if ("".equals(this.txtRfc.getText())) {
                Mensaje.error(this, "Campo de RFC no se ha llenado");
            } else if (txtRfc.getText().length() < 12 || txtRfc.getText().length() > 13) {
                Mensaje.error(this, "Faltan o sobran digitos en el campo de RFC, compruebe");
            } else {
                cantP = this.ferrD.cantidadP(this.prod_idP);
                if (Integer.parseInt(txtCantP.getText()) <= 0 || Integer.parseInt(txtCantP.getText()) > cantP) {
                    Mensaje.error(this, "Cantidad incorrecta");
                    CtrlInterfaz.cambia(txtCantP);
                } else {
                    if (conexion.getAutoCommit()) {
                        conexion.setAutoCommit(false);
                    }
                    this.prod_idP = Integer.parseInt(String.valueOf(this.comboBoxProd.getSelectedItem()));
                    Productos p = this.ferrD.listaPWhere(this.prod_idP);

                    int idPV;
                    do {
                        idPV = generaIdPV();
                    } while (idPV == -1);

                    double mont = p.getPrecio();
                    this.total = (mont * Integer.parseInt(txtCantP.getText()));
                    double iva = calculaIva(total);
                    double totalIva = this.total + iva;
                    int idV = generaNumVent();
                    String prod = p.getNombre();
                    updateCant = cantP - Integer.parseInt(txtCantP.getText());

                    ferrDaoT.insertVent(idV, mont, totalIva);
                    ferrDaoT.insertProductoVen(idPV, this.prod_idP, idV, this.vend_idV);
//                    fn.add(new FacturaNota(generaNumFac(), prod, Integer.parseInt(txtCantP.getText()), txtRfc.getText().toUpperCase(), iva, idPV));
                    ferrDaoT.insertFacturaN(generaNumFac(), prod, Integer.parseInt(txtCantP.getText()), txtRfc.getText().toUpperCase(), iva, idPV);
                    ferrDaoT.actualizarPcant(updateCant, this.prod_idP);

                    String s = txtDteVn.getText() + "Producto: " + prod + "\nPrecio: "
                            + mont + "\nCantidad: " + txtCantP.getText() + "\n";
                    txtDteVn.setText(s);
                    CtrlInterfaz.limpia(txtAVta, txtCantP);
                    CtrlInterfaz.cambia(btnConfirmarF);
                    CtrlInterfaz.habilita(false, btnAgregar);
                    CtrlInterfaz.habilita(true, btnConfirmarF);
                    comboBoxProd.setSelectedIndex(0);
                }
            }
        } catch (Exception e) {
            Mensaje.error(this, "Verifique los datos, no esta seleccionando producto o no esta llenando el campo de cantidad");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    private void txtRfcKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtRfcKeyPressed
    {//GEN-HEADEREND:event_txtRfcKeyPressed
        String s = "";
        if (evt.getKeyChar() == '\n') {
            if (txtRfc.getText().equals(s)) {
                Mensaje.error(this, "El campo no puede estar vacío");
            } else if (txtRfc.getText().length() < 12 || txtRfc.getText().length() > 13) {
                Mensaje.error(this, "Faltan o sobran digitos, compruebe");
            } else {
                Validaciones.enter(this, evt, this.comboBoxProd);
            }
        }
    }//GEN-LAST:event_txtRfcKeyPressed

    private void btnCancelarFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarFActionPerformed
    {//GEN-HEADEREND:event_btnCancelarFActionPerformed
        CtrlInterfaz.limpia(txtRfc, txtCantP, btnAgregar, btnConfirmarF, txtDteVn, txtAVta);
        CtrlInterfaz.habilita(false, comboBoxProd, txtRfc, txtCantP, btnAgregar, btnConfirmarF);
        this.comboBoxProd.setSelectedIndex(0);
        this.comboBoxVend.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarFActionPerformed

    private void txtRfcKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtRfcKeyTyped
    {//GEN-HEADEREND:event_txtRfcKeyTyped
        Validaciones.validaAlfanumerico(evt, 13, txtRfc.getText());
    }//GEN-LAST:event_txtRfcKeyTyped

    private void txtCantPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCantPKeyTyped
    {//GEN-HEADEREND:event_txtCantPKeyTyped
        Validaciones.validaEntero(evt, 6, txtCantP.getText());
    }//GEN-LAST:event_txtCantPKeyTyped

    private void txtCantPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCantPKeyPressed
    {//GEN-HEADEREND:event_txtCantPKeyPressed
        try {
            if (evt.getKeyChar() == '\n') {
                if (Integer.parseInt(txtCantP.getText()) <= 0) {
                    Mensaje.error(this, "Las existencias no pueden se negativas ni cero");
                    CtrlInterfaz.cambia(txtCantP);
                } else {
                    Validaciones.enterEntero(this, evt, txtCantP, btnAgregar);
                }
            }
        } catch (Exception e) {
            Validaciones.enter(this, evt, txtCantP, txtCantP, "Capo vacío");
        }
    }//GEN-LAST:event_txtCantPKeyPressed

    private void txtCantPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtCantPActionPerformed
    {//GEN-HEADEREND:event_txtCantPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantPActionPerformed

    private void btnConfirmarFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConfirmarFActionPerformed
    {//GEN-HEADEREND:event_btnConfirmarFActionPerformed
        try {
            if (Mensaje.pregunta(this, "Desea Confirmar la venta?") == 0) {
                this.conexion.commit();
                total = 0;
                Mensaje.exito(this, "Venta realizada con exito!");
                btnCancelarFActionPerformed(evt);
            } else {
                this.conexion.rollback();
                Mensaje.error(this, "Operacion cancelada");
                btnCancelarFActionPerformed(evt);
            }
        } catch (SQLException ex) {
            //ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnConfirmarFActionPerformed

    private void comboBoxProdMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboBoxProdMousePressed
    {//GEN-HEADEREND:event_comboBoxProdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxProdMousePressed

    private void btnAgregarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAgregarKeyPressed
    {//GEN-HEADEREND:event_btnAgregarKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnAgregarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAgregarKeyPressed

    private void comboBoxProdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboBoxProdActionPerformed
    {//GEN-HEADEREND:event_comboBoxProdActionPerformed
        try {
            if (this.comboBoxProd.getSelectedIndex() != 0) {
                String desp = "";
                this.vend_idV = Integer.parseInt(String.valueOf(this.comboBoxVend.getSelectedItem()));
                Vendedor v = this.ferrD.listaVendWhere(this.vend_idV);
                desp += v.desp();

                this.prod_idP = Integer.parseInt(String.valueOf(this.comboBoxProd.getSelectedItem()));
                Productos p = this.ferrD.listaPWhere(this.prod_idP);
                desp += p.toString();
                txtAVta.setText(desp);
                CtrlInterfaz.habilita(true, txtCantP);
                CtrlInterfaz.cambia(this.txtCantP);
            } else {
                CtrlInterfaz.habilita(false, txtCantP);
                comboBoxVendActionPerformed(evt);
            }

        } catch (Exception e) {
            //e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_comboBoxProdActionPerformed


    private void btnConfirmarFKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnConfirmarFKeyPressed
    {//GEN-HEADEREND:event_btnConfirmarFKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnConfirmarFActionPerformed(null);
        }
    }//GEN-LAST:event_btnConfirmarFKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        try {
            llenaComboProd();
            llenaComboVend();
        } catch (Exception e) {
            Mensaje.error(this, "Aún no hay registros");
            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void comboBoxVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVendActionPerformed
        try {
            if (this.comboBoxVend.getSelectedIndex() != 0) {
                this.vend_idV = Integer.parseInt(String.valueOf(this.comboBoxVend.getSelectedItem()));
                Vendedor v = this.ferrD.listaVendWhere(this.vend_idV);
                txtAVta.setText(v.desp());
                CtrlInterfaz.habilita(true, this.txtRfc);
                CtrlInterfaz.cambia(this.txtRfc);
            } else {
                CtrlInterfaz.limpia(txtCantP, txtAVta);
                CtrlInterfaz.habilita(false, comboBoxProd, txtRfc, txtCantP, btnAgregar);
                this.comboBoxProd.setSelectedIndex(0);
            }

        } catch (Exception e) {
//            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_comboBoxVendActionPerformed

    public void llenaComboProd() {
        List<Integer> arr = ferrD.listaIdP();
        for (int idP : arr) {
            this.comboBoxProd.addItem(String.valueOf(idP));
        }
    }

    public void llenaComboVend() {
        List<Integer> arr = ferrD.listaVendId();
        for (int idVend : arr) {
            this.comboBoxVend.addItem(String.valueOf(idVend));
        }
    }

    public int generaNumFac() {
        int num = (int) (Math.random() * 1000);
        String uno = "1" + num;
        int numF = Integer.parseInt(uno);
        return numF;
    }

    public int generaNumVent() {
        int num = (int) (Math.random() * 1000);
        String uno = "3" + num;
        int numF = Integer.parseInt(uno);
        return numF;
    }

    public int generaIdPV() {
        int numF = -1;
        try {
            int num = (int) (Math.random() * 1000);
            String uno = "4" + num;
            numF = Integer.parseInt(uno);
        } catch (Exception e) {

        }
        return numF;
    }

    public double calculaIva(double total) {
        double iva;
        iva = total * 0.16;
        return iva;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnFactura().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelarF;
    private javax.swing.JButton btnConfirmarF;
    private javax.swing.JComboBox<String> comboBoxProd;
    private javax.swing.JComboBox<String> comboBoxVend;
    private javax.swing.JLabel etqCantP;
    private javax.swing.JLabel etqCantP1;
    private javax.swing.JLabel etqCveVend;
    private javax.swing.JLabel etqDetV;
    private javax.swing.JLabel etqDetV1;
    private javax.swing.JLabel etqFactura;
    private javax.swing.JLabel etqRfc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPanel panelGis;
    private javax.swing.JTextArea txtAVta;
    private javax.swing.JTextField txtCantP;
    private javax.swing.JTextArea txtDteVn;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
}
