/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

import cjb.ci.*;
import datos.FerreteriaDAO;
import domain.*;
import java.util.*;

/**
 *
 * @author Rafael
 */
public class VtnFactura extends javax.swing.JFrame {

    FerreteriaDAO ferrD = new FerreteriaDAO();
    int prod_idP, vend_idV, idVenta = -1, cantidadP = -1;
    String cliente_rfc;
    double monto;

    List<ProductoVenta> listPV = new ArrayList<>();

    /**
     * Creates new form VtnFactura
     */
    public VtnFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGis = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCancelarF = new javax.swing.JButton();
        txtCantP = new javax.swing.JTextField();
        btnConfirmarF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelBlanco = new javax.swing.JPanel();
        etqFactura = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAVta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDteVn = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        etqDetV = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        etqDetV1 = new javax.swing.JLabel();
        comboBoxVend = new javax.swing.JComboBox<>();
        comboBoxRFC = new javax.swing.JComboBox<>();
        etqCantP = new javax.swing.JLabel();
        comboBoxProd = new javax.swing.JComboBox<>();
        etqCveVend = new javax.swing.JLabel();
        etqRfc = new javax.swing.JLabel();
        etqCantP1 = new javax.swing.JLabel();
        madera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Factura");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGis.setBackground(new java.awt.Color(0, 0, 0));
        panelGis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(51, 153, 0));
        btnAgregar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregarKeyPressed(evt);
            }
        });
        panelGis.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        btnCancelarF.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarF.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCancelarF.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarF.setText("Cancelar");
        btnCancelarF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFActionPerformed(evt);
            }
        });
        panelGis.add(btnCancelarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        txtCantP.setEnabled(false);
        txtCantP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantPKeyTyped(evt);
            }
        });
        panelGis.add(txtCantP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 80, -1));

        btnConfirmarF.setBackground(new java.awt.Color(51, 153, 0));
        btnConfirmarF.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnConfirmarF.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarF.setText("Confirmar");
        btnConfirmarF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirmarF.setEnabled(false);
        btnConfirmarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarFActionPerformed(evt);
            }
        });
        btnConfirmarF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmarFKeyPressed(evt);
            }
        });
        panelGis.add(btnConfirmarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqFactura.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        etqFactura.setForeground(new java.awt.Color(0, 0, 0));
        etqFactura.setText("Factura");
        panelBlanco.add(etqFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 19, -1, 31));

        jPanel1.add(panelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -10, 210, 60));

        txtAVta.setEditable(false);
        txtAVta.setColumns(20);
        txtAVta.setRows(5);
        jScrollPane2.setViewportView(txtAVta);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 380, 210));

        txtDteVn.setEditable(false);
        txtDteVn.setColumns(20);
        txtDteVn.setRows(5);
        jScrollPane3.setViewportView(txtDteVn);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 340, 210));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        etqDetV.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        etqDetV.setForeground(new java.awt.Color(255, 255, 255));
        etqDetV.setText("Venta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(etqDetV)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqDetV)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 80, 50));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        etqDetV1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        etqDetV1.setForeground(new java.awt.Color(255, 255, 255));
        etqDetV1.setText("Detalle de venta:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqDetV1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqDetV1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 140, 50));

        comboBoxVend.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxVend.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxVend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el vendedor" }));
        comboBoxVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVendActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, -1));

        comboBoxRFC.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxRFC.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxRFC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el RFC" }));
        comboBoxRFC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboBoxRFC.setEnabled(false);
        comboBoxRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRFCActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 20));

        etqCantP.setBackground(new java.awt.Color(0, 0, 0));
        etqCantP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etqCantP.setForeground(new java.awt.Color(0, 0, 0));
        etqCantP.setText("Producto:");
        jPanel1.add(etqCantP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        comboBoxProd.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxProd.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona tu producto" }));
        comboBoxProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboBoxProd.setEnabled(false);
        comboBoxProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProdActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 170, 20));

        etqCveVend.setBackground(new java.awt.Color(0, 0, 0));
        etqCveVend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etqCveVend.setForeground(new java.awt.Color(0, 0, 0));
        etqCveVend.setText("Clave del vendedor: ");
        jPanel1.add(etqCveVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        etqRfc.setBackground(new java.awt.Color(0, 0, 0));
        etqRfc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etqRfc.setForeground(new java.awt.Color(0, 0, 0));
        etqRfc.setText("RFC: ");
        jPanel1.add(etqRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        etqCantP1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etqCantP1.setForeground(new java.awt.Color(0, 0, 0));
        etqCantP1.setText("Cantidad:");
        jPanel1.add(etqCantP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        madera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maderaBlanca.jpg"))); // NOI18N
        jPanel1.add(madera, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1060, 480));

        panelGis.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1020, 380));

        getContentPane().add(panelGis, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -3, 1060, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        try {
            int cant = this.cantidadP == -1 ? this.ferrD.cantidadP(this.prod_idP) : this.cantidadP;
            if (Integer.parseInt(txtCantP.getText()) <= 0 || Integer.parseInt(txtCantP.getText()) > cant) {
                Mensaje.error(this, "No puede ser menor o igual a 0, o la petición excede las existencias.");
                CtrlInterfaz.cambia(txtCantP);
            } else {
                this.prod_idP = Integer.parseInt(String.valueOf(this.comboBoxProd.getSelectedItem()));
                Productos p = this.ferrD.listaPWhere(this.prod_idP);
                if (this.idVenta == -1) {
                    this.idVenta = generaNumVent();
                }
                boolean b = validaProd();
                int cantidadT;
                int cantTxt = Integer.parseInt(this.txtCantP.getText());

                if (!b) {
                    listPV.add(new ProductoVenta(this.prod_idP, this.idVenta, Integer.parseInt(txtCantP.getText())));
                } else {
                    for (ProductoVenta pv : listPV) {
                        if (this.prod_idP == pv.getIdProd()) {
                            cantidadT = cantTxt + pv.getCantidad();
                            pv.setCantidad(cantidadT);
                            break;
                        }
                    }
                }

                double mont = p.getPrecio();
                this.monto += (mont * Integer.parseInt(txtCantP.getText()));
                String s = txtDteVn.getText() + "Producto: " + p.getNombre() + "\nPrecio: "
                        + mont + "\nCantidad: " + txtCantP.getText()
                        + "\n------------------------------------\n";
                txtDteVn.setText(s);
                CtrlInterfaz.limpia(txtCantP);
                CtrlInterfaz.cambia(btnConfirmarF);
                CtrlInterfaz.habilita(false, btnAgregar, comboBoxVend, comboBoxRFC);
                CtrlInterfaz.habilita(true, btnConfirmarF);
                comboBoxProd.setSelectedIndex(0);
            }
        } catch (Exception e) {
            Mensaje.error(this, "Verifique los datos, no esta seleccionando producto o no esta llenando el campo de cantidad");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private boolean validaProd() {
        boolean b = false;
        if (!listPV.isEmpty()) {
            for (ProductoVenta pv : listPV) {
                if (this.prod_idP == pv.getIdProd()) {
                    b = true;
                    break;
                } else {
                    b = false;
                }
            }
        }
        return b;
    }


    private void btnCancelarFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarFActionPerformed
    {//GEN-HEADEREND:event_btnCancelarFActionPerformed
        CtrlInterfaz.limpia(txtCantP, btnAgregar, btnConfirmarF, txtDteVn, txtAVta);
        CtrlInterfaz.habilita(false, comboBoxRFC, comboBoxProd, txtCantP, btnAgregar, btnConfirmarF);
        CtrlInterfaz.habilita(true, comboBoxVend);
        this.comboBoxVend.setSelectedIndex(0);
        this.comboBoxRFC.setSelectedIndex(0);
        this.comboBoxProd.setSelectedIndex(0);
        this.cantidadP = -1;
        this.idVenta = -1;
        this.monto = 0;
        listPV.clear();
    }//GEN-LAST:event_btnCancelarFActionPerformed

    private void txtCantPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCantPKeyTyped
    {//GEN-HEADEREND:event_txtCantPKeyTyped
        Validaciones.validaEntero(evt, 6, txtCantP.getText());
    }//GEN-LAST:event_txtCantPKeyTyped

    private void txtCantPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCantPKeyPressed
    {//GEN-HEADEREND:event_txtCantPKeyPressed
        try {
            if (evt.getKeyChar() == '\n') {
                if (Integer.parseInt(txtCantP.getText()) <= 0) {
                    Mensaje.error(this, "Las existencias no pueden se negativas ni cero");
                    CtrlInterfaz.cambia(txtCantP);
                } else {
                    Validaciones.enterEntero(this, evt, txtCantP, btnAgregar);
                }
            }
        } catch (Exception e) {
            Validaciones.enter(this, evt, txtCantP, txtCantP, "Capo vacío");
        }
    }//GEN-LAST:event_txtCantPKeyPressed

    private void btnConfirmarFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConfirmarFActionPerformed
    {//GEN-HEADEREND:event_btnConfirmarFActionPerformed
        if (Mensaje.pregunta(this, "Desea Confirmar la venta?") == 0) {
            double iva = calculaIva(monto);
            double total = monto + iva;
            this.ferrD.insertVent(idVenta, monto, total,
                    Integer.parseInt(String.valueOf(comboBoxVend.getSelectedItem())));

            int cantidadAct;
            for (ProductoVenta pv : this.listPV) {
                this.ferrD.insertProductoVen(pv.getIdProd(), pv.getIdVenta(), pv.getCantidad());
                cantidadAct = this.ferrD.listaCantidadP(pv.getIdProd()) - pv.getCantidad();
                this.ferrD.actualizarPcant(cantidadAct, pv.getIdProd());
            }
            int idCliente = this.ferrD.selectIdClienteRfc(String.valueOf(this.comboBoxRFC.getSelectedItem()));
            this.ferrD.insertFacturaN(generaNumFac(), String.valueOf(this.comboBoxRFC.getSelectedItem()), iva, this.idVenta, idCliente);
            Mensaje.exito(this, "Venta realizada con exito!");
            btnCancelarFActionPerformed(evt);
        } else {
            Mensaje.error(this, "Operacion cancelada");
            btnCancelarFActionPerformed(evt);
        }
    }//GEN-LAST:event_btnConfirmarFActionPerformed

    private void btnAgregarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAgregarKeyPressed
    {//GEN-HEADEREND:event_btnAgregarKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnAgregarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAgregarKeyPressed

    private void comboBoxRFCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboBoxRFCActionPerformed
    {//GEN-HEADEREND:event_comboBoxRFCActionPerformed
        try {
            if (this.comboBoxRFC.getSelectedIndex() != 0) {
                this.comboBoxProd.setSelectedIndex(0);
                String desp = this.vendedorDesp() + this.clienteDesp();
                txtAVta.setText(desp);
                CtrlInterfaz.habilita(true, comboBoxProd);
            } else {
                CtrlInterfaz.limpia(txtCantP);
                CtrlInterfaz.habilita(false, comboBoxProd, txtCantP, btnAgregar);
                this.comboBoxProd.setSelectedIndex(0);
                comboBoxVendActionPerformed(evt);
            }
        } catch (Exception e) {
            //e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_comboBoxRFCActionPerformed


    private void btnConfirmarFKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnConfirmarFKeyPressed
    {//GEN-HEADEREND:event_btnConfirmarFKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnConfirmarFActionPerformed(null);
        }
    }//GEN-LAST:event_btnConfirmarFKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        try {
            llenaComboVend();
            llenaComboRfc();
            llenaComboProd();
        } catch (Exception e) {
            Mensaje.error(this, "Aún no hay registros");
            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void comboBoxVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVendActionPerformed
        try {
            if (this.comboBoxVend.getSelectedIndex() != 0) {
                this.comboBoxRFC.setSelectedIndex(0);
                this.comboBoxProd.setSelectedIndex(0);
                txtAVta.setText(vendedorDesp());
                CtrlInterfaz.habilita(true, this.comboBoxRFC);
                CtrlInterfaz.cambia(this.comboBoxRFC);
            } else {
                CtrlInterfaz.limpia(txtCantP, txtAVta);
                CtrlInterfaz.habilita(false, comboBoxRFC, comboBoxProd, txtCantP, btnAgregar);
                this.comboBoxRFC.setSelectedIndex(0);
                this.comboBoxProd.setSelectedIndex(0);
            }
        } catch (Exception e) {
//            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_comboBoxVendActionPerformed

    private void comboBoxProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxProdActionPerformed
        try {
            if (this.comboBoxProd.getSelectedIndex() != 0) {
                String desp = this.vendedorDesp() + this.clienteDesp() + this.productoDesp();
                txtAVta.setText(desp);
                CtrlInterfaz.habilita(true, txtCantP);
                CtrlInterfaz.cambia(this.txtCantP);
            } else {
                CtrlInterfaz.limpia(txtCantP);
                CtrlInterfaz.habilita(false, txtCantP, btnAgregar);
                comboBoxRFCActionPerformed(evt);
            }
        } catch (Exception e) {
            //e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_comboBoxProdActionPerformed

    private String vendedorDesp() {
        this.vend_idV = Integer.parseInt(String.valueOf(this.comboBoxVend.getSelectedItem()));
        Vendedor v = this.ferrD.listaVendWhere(this.vend_idV);
        return v.desp();
    }

    private String productoDesp() {
        this.prod_idP = Integer.parseInt(String.valueOf(this.comboBoxProd.getSelectedItem()));
        Productos p = this.ferrD.listaPWhere(this.prod_idP);
        int cantidadT;
        if (listPV.size() != 0) {
            for (ProductoVenta pv : listPV) {
                if (this.prod_idP == pv.getIdProd()) {
                    cantidadT = p.getCantidad() - pv.getCantidad();
                    this.cantidadP = cantidadT;
                    p.setCantidad(cantidadT);
                    break;
                }
            }
        }
        return p.toString();
    }

    private String clienteDesp() {
        this.cliente_rfc = String.valueOf(this.comboBoxRFC.getSelectedItem());
        Cliente c = this.ferrD.listaClienteWhereRFC(this.cliente_rfc);
        return c.desp();
    }

    private void llenaComboProd() {
        List<Integer> arr = ferrD.listaIdP();
        for (int idP : arr) {
            this.comboBoxProd.addItem(String.valueOf(idP));
        }
    }

    private void llenaComboVend() {
        List<Integer> arr = ferrD.listaVendId();
        for (int idVend : arr) {
            this.comboBoxVend.addItem(String.valueOf(idVend));
        }
    }

    private void llenaComboRfc() {
        List<String> arr = ferrD.listaRFCliente();
        for (String rfc : arr) {
            this.comboBoxRFC.addItem(rfc);
        }
    }

    private int generaNumFac() {
        boolean b = false;
        int numF = 0;
        while (!b) {
            int num = (int) (Math.random() * 10000);
            String uno = "1" + num;
            numF = Integer.parseInt(uno);
            int idFactNota = this.ferrD.listaFacturaNotaWhereID(numF);
            b = idFactNota == 0 ? true : false;
        }
        return numF;
    }

    private int generaNumVent() {
        boolean b = false;
        int numF = 0;
        while (!b) {
            int num = (int) (Math.random() * 10000);
            String uno = "3" + num;
            numF = Integer.parseInt(uno);
            int idVendedor = this.ferrD.listaVendWhereID(numF);
            b = idVendedor == 0 ? true : false;
        }
        return numF;
    }

    private double calculaIva(double total) {
        double iva;
        iva = total * 0.16;
        return iva;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnFactura().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelarF;
    private javax.swing.JButton btnConfirmarF;
    private javax.swing.JComboBox<String> comboBoxProd;
    private javax.swing.JComboBox<String> comboBoxRFC;
    private javax.swing.JComboBox<String> comboBoxVend;
    private javax.swing.JLabel etqCantP;
    private javax.swing.JLabel etqCantP1;
    private javax.swing.JLabel etqCveVend;
    private javax.swing.JLabel etqDetV;
    private javax.swing.JLabel etqDetV1;
    private javax.swing.JLabel etqFactura;
    private javax.swing.JLabel etqRfc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel madera;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPanel panelGis;
    private javax.swing.JTextArea txtAVta;
    private javax.swing.JTextField txtCantP;
    private javax.swing.JTextArea txtDteVn;
    // End of variables declaration//GEN-END:variables
}
