/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author rafael
 */
public class VtnInicio extends javax.swing.JFrame {

    /**
     * Creates new form VtnInicio
     */
    public VtnInicio() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(getIconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        etqBienvenido = new javax.swing.JLabel();
        etqBienvenido1 = new javax.swing.JLabel();
        madera = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        maderaSalir = new javax.swing.JLabel();
        imgInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("inicioMenu");
        setBackground(new java.awt.Color(153, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 667));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciar1.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciar1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnIniciar1.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciar1.setText("Iniciar");
        btnIniciar1.setToolTipText("Iniciar punto de venta");
        btnIniciar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 90, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqBienvenido.setFont(new java.awt.Font("Lucida Handwriting", 3, 48)); // NOI18N
        etqBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        etqBienvenido.setText("¡Bienvenido!");
        jPanel1.add(etqBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 380, -1));

        etqBienvenido1.setFont(new java.awt.Font("Lucida Handwriting", 3, 48)); // NOI18N
        etqBienvenido1.setForeground(new java.awt.Color(0, 0, 0));
        etqBienvenido1.setText("¡Bienvenido!");
        jPanel1.add(etqBienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, -1));

        madera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maderaOscura.jpg"))); // NOI18N
        madera.setText("jLabel1");
        jPanel1.add(madera, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 450, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 420, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Salir");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 47, 70, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Salir");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 70, 40));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/madera3.jpg"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Salir del programa");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 90, 40));

        maderaSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        getContentPane().add(maderaSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, -60, -1, -1));

        imgInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/incio.png"))); // NOI18N
        getContentPane().add(imgInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar1ActionPerformed
        VtnPrincipal obj = new VtnPrincipal();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciar1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnInicio().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image obj = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
        return obj;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel etqBienvenido;
    private javax.swing.JLabel etqBienvenido1;
    private javax.swing.JLabel imgInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel madera;
    private javax.swing.JLabel maderaSalir;
    // End of variables declaration//GEN-END:variables
}
