/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisVtnP;

import cjb.ci.*;
import static datos.Conexion.getConnection;
import datos.FerreteriaDAO;
import domain.*;
import java.sql.*;
import java.util.List;

/**
 *
 * @author Rafael
 */
public class VtnNota extends javax.swing.JFrame {

    double total;
    int pos, prod_idP, vend_idV;
    FerreteriaDAO ferrD = new FerreteriaDAO();

    Connection conexion = getConnection();
    FerreteriaDAO ferrDaoT = new FerreteriaDAO(conexion);

    /**
     * Creates new form VtnFactura
     */
    public VtnNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGis = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCantP = new javax.swing.JTextField();
        etqCantP1 = new javax.swing.JLabel();
        btnConfirmarN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelBlanco = new javax.swing.JPanel();
        etqFactura = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAVta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDteVn = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        etqDetV = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        etqDetV1 = new javax.swing.JLabel();
        etqCveVend = new javax.swing.JLabel();
        etqCantP = new javax.swing.JLabel();
        comboBoxProd = new javax.swing.JComboBox<>();
        txtDescuento = new javax.swing.JTextField();
        cbDescuento = new javax.swing.JCheckBox();
        comboBoxVend = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Factura");
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGis.setBackground(new java.awt.Color(153, 153, 0));
        panelGis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(51, 153, 0));
        btnAgregar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregarKeyPressed(evt);
            }
        });
        panelGis.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelGis.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        txtCantP.setEnabled(false);
        txtCantP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantPActionPerformed(evt);
            }
        });
        txtCantP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantPKeyTyped(evt);
            }
        });
        panelGis.add(txtCantP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 80, -1));

        etqCantP1.setForeground(new java.awt.Color(0, 0, 0));
        etqCantP1.setText("Cantidad:");
        panelGis.add(etqCantP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        btnConfirmarN.setBackground(new java.awt.Color(51, 153, 0));
        btnConfirmarN.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnConfirmarN.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarN.setText("Confirmar");
        btnConfirmarN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirmarN.setEnabled(false);
        btnConfirmarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarNActionPerformed(evt);
            }
        });
        btnConfirmarN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmarNKeyPressed(evt);
            }
        });
        panelGis.add(btnConfirmarN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqFactura.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        etqFactura.setText("Nota");
        panelBlanco.add(etqFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 31));

        jPanel1.add(panelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -10, 210, 60));

        txtAVta.setEditable(false);
        txtAVta.setColumns(20);
        txtAVta.setRows(5);
        jScrollPane2.setViewportView(txtAVta);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 380, 210));

        txtDteVn.setEditable(false);
        txtDteVn.setColumns(20);
        txtDteVn.setRows(5);
        jScrollPane3.setViewportView(txtDteVn);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 340, 210));

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));

        etqDetV.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        etqDetV.setForeground(new java.awt.Color(255, 255, 255));
        etqDetV.setText("Venta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(etqDetV)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqDetV)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 80, 50));

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));

        etqDetV1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        etqDetV1.setForeground(new java.awt.Color(255, 255, 255));
        etqDetV1.setText("Detalle de venta:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqDetV1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqDetV1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 140, 50));

        etqCveVend.setForeground(new java.awt.Color(0, 0, 0));
        etqCveVend.setText("Clave del vendedor: ");
        jPanel1.add(etqCveVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        etqCantP.setForeground(new java.awt.Color(0, 0, 0));
        etqCantP.setText("Producto:");
        jPanel1.add(etqCantP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        comboBoxProd.setBackground(new java.awt.Color(204, 255, 255));
        comboBoxProd.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione productos" }));
        comboBoxProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboBoxProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboBoxProdMousePressed(evt);
            }
        });
        comboBoxProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProdActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, -1));

        txtDescuento.setEnabled(false);
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyTyped(evt);
            }
        });
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 100, -1));

        cbDescuento.setForeground(new java.awt.Color(0, 0, 0));
        cbDescuento.setText("Descuento");
        cbDescuento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(cbDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        comboBoxVend.setBackground(new java.awt.Color(255, 255, 153));
        comboBoxVend.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxVend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el vendedor" }));
        comboBoxVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVendActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        panelGis.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1020, 380));

        getContentPane().add(panelGis, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -3, 1060, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        try {
            int cantP = this.ferrD.cantidadP(this.prod_idP);
            if (Integer.parseInt(txtCantP.getText()) <= 0 || Integer.parseInt(txtCantP.getText()) > cantP) {
                Mensaje.error(this, "Cantidad incorrecta");
                CtrlInterfaz.cambia(txtCantP);
            } else {
                if (conexion.getAutoCommit()) {
                    conexion.setAutoCommit(false);
                }

                int desc = 0;
                if (txtDescuento.getText() == null || txtDescuento.isEnabled() == false) {
                    desc = 0;
                } else {
                    try {
                        desc = Integer.parseInt(String.valueOf(txtDescuento.getText()));
                    } catch (Exception e) {
                        desc = 0;
                    }
                }

                this.prod_idP = Integer.parseInt(String.valueOf(this.comboBoxProd.getSelectedItem()));
                Productos p = this.ferrD.listaPWhere(this.prod_idP);

                int idPV = generaIdPV();
                double mont = p.getPrecio();
                this.total = (mont * Integer.parseInt(txtCantP.getText()));
                double descuento = calcDesc(this.total, desc);
                double totalD = this.total - descuento;
                int idV = generaNumVent();
                String prod = p.getNombre();
                int updateCant = cantP - Integer.parseInt(txtCantP.getText());

//                ferrDaoT.insertVent(idV, mont, totalD);
//                ferrDaoT.insertProductoVen(idPV, this.prod_idP, idV, this.vend_idV);
//                ferrDaoT.insertNota(generaNumNot(), prod, Integer.parseInt(txtCantP.getText()), desc, idPV);
//                ferrDaoT.actualizarPcant(updateCant, this.prod_idP);
                String s = txtDteVn.getText() + "Producto: " + prod + "\nPrecio: "
                        + mont + "\nCantidad: " + txtCantP.getText() + "\n";
                txtDteVn.setText(s);
                CtrlInterfaz.limpia(txtAVta, txtCantP);
                CtrlInterfaz.cambia(btnConfirmarN);
                CtrlInterfaz.habilita(false, btnAgregar);
                CtrlInterfaz.habilita(true, btnConfirmarN);
                comboBoxProd.setSelectedIndex(0);
            }
        } catch (Exception e) {
            Mensaje.error(this, "Verifique los datos, no esta seleccionando producto o no esta llenando el campo de cantidad");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        CtrlInterfaz.limpia(txtDescuento, txtCantP, btnAgregar, btnConfirmarN, txtDteVn, txtAVta);
        CtrlInterfaz.habilita(false, txtDescuento, txtCantP, btnAgregar, btnConfirmarN);
        cbDescuento.setSelected(false);
        comboBoxVend.setSelectedIndex(0);
        comboBoxProd.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCantPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCantPKeyTyped
    {//GEN-HEADEREND:event_txtCantPKeyTyped
        Validaciones.validaEntero(evt, 6, txtCantP.getText());
    }//GEN-LAST:event_txtCantPKeyTyped

    private void txtCantPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCantPKeyPressed
    {//GEN-HEADEREND:event_txtCantPKeyPressed
        try {
            if (evt.getKeyChar() == '\n') {
                if (Integer.parseInt(txtCantP.getText()) <= 0) {
                    Mensaje.error(this, "La cantidad de productos no pueden ser cero");
                    CtrlInterfaz.cambia(txtCantP);
                } else {
                    Validaciones.enterEntero(this, evt, txtCantP, btnAgregar);
                }
            }

        } catch (Exception e) {
            Validaciones.enter(this, evt, txtCantP, txtCantP, "Capo vacío");
        }
    }//GEN-LAST:event_txtCantPKeyPressed

    private void txtCantPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtCantPActionPerformed
    {//GEN-HEADEREND:event_txtCantPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantPActionPerformed

    private void btnConfirmarNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConfirmarNActionPerformed
    {//GEN-HEADEREND:event_btnConfirmarNActionPerformed
        try {
            if (Mensaje.pregunta(this, "Desea Confirmar la venta?") == 0) {
                this.conexion.commit();
                total = 0;
                Mensaje.exito(this, "Venta realizada con exito!");
                btnCancelarActionPerformed(evt);
                comboBoxVend.setSelectedIndex(0);
                comboBoxProd.setSelectedIndex(0);

            } else {
                this.conexion.rollback();
                Mensaje.error(this, "Operacion cancelada");
                comboBoxVend.setSelectedIndex(0);
                comboBoxProd.setSelectedIndex(0);
                btnCancelarActionPerformed(evt);
            }
        } catch (SQLException ex) {
//            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnConfirmarNActionPerformed

    private void comboBoxProdMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboBoxProdMousePressed
    {//GEN-HEADEREND:event_comboBoxProdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxProdMousePressed

    private void btnAgregarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAgregarKeyPressed
    {//GEN-HEADEREND:event_btnAgregarKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnAgregarActionPerformed(null);
        }

    }//GEN-LAST:event_btnAgregarKeyPressed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtDescuentoActionPerformed
    {//GEN-HEADEREND:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtDescuentoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtDescuentoKeyPressed
    {//GEN-HEADEREND:event_txtDescuentoKeyPressed
        try {
            if (evt.getKeyChar() == '\n') {
                if (Double.parseDouble(txtDescuento.getText()) <= 0 || Double.parseDouble(txtDescuento.getText()) >= 100) {
                    Mensaje.error(this, "El descuento no pueden ser cero o mayor al total");
                    CtrlInterfaz.cambia(txtDescuento);
                } else {
                    Validaciones.enterFlotante(this, evt, txtDescuento, txtCantP);
                }
            }

        } catch (Exception e) {
            Validaciones.enter(this, evt, txtDescuento, txtDescuento, "Capo vacío");
        }
    }//GEN-LAST:event_txtDescuentoKeyPressed

    private void txtDescuentoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtDescuentoKeyTyped
    {//GEN-HEADEREND:event_txtDescuentoKeyTyped
        Validaciones.validaEntero(evt, 5, txtDescuento.getText());
    }//GEN-LAST:event_txtDescuentoKeyTyped

    private void cbDescuentoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbDescuentoActionPerformed
    {//GEN-HEADEREND:event_cbDescuentoActionPerformed
        if (cbDescuento.isSelected()) {
            cbDescuento.setSelected(rootPaneCheckingEnabled);
            CtrlInterfaz.habilita(true, txtDescuento);
        } else {
            CtrlInterfaz.habilita(false, txtDescuento);
        }
    }//GEN-LAST:event_cbDescuentoActionPerformed

    private void btnConfirmarNKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnConfirmarNKeyPressed
    {//GEN-HEADEREND:event_btnConfirmarNKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnConfirmarNActionPerformed(null);
        }
    }//GEN-LAST:event_btnConfirmarNKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        try {
            llenaComboVend();
            llenaComboProd();
        } catch (Exception e) {
            Mensaje.error(this, "Aún no hay registros");
            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void comboBoxProdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboBoxProdActionPerformed
    {//GEN-HEADEREND:event_comboBoxProdActionPerformed
        try {
            String desp = "";
            this.vend_idV = Integer.parseInt(String.valueOf(this.comboBoxVend.getSelectedItem()));
            Vendedor v = this.ferrD.listaVendWhere(this.vend_idV);
            desp += v.desp();

            this.prod_idP = Integer.parseInt(String.valueOf(this.comboBoxProd.getSelectedItem()));
            Productos p = this.ferrD.listaPWhere(this.prod_idP);
            desp += p.toString();
            txtAVta.setText(desp);
            CtrlInterfaz.habilita(true, txtCantP);
        } catch (Exception e) {
            //e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_comboBoxProdActionPerformed

    private void comboBoxVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVendActionPerformed
        try {
            this.comboBoxProd.setSelectedIndex(0);
            this.vend_idV = Integer.parseInt(String.valueOf(this.comboBoxVend.getSelectedItem()));
            Vendedor v = this.ferrD.listaVendWhere(this.vend_idV);
            txtAVta.setText(v.desp());
            CtrlInterfaz.habilita(true, this.comboBoxProd);
        } catch (Exception e) {
//            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_comboBoxVendActionPerformed

    public void llenaComboProd() {
        List<Integer> arr = ferrD.listaIdP();
        for (int idP : arr) {
            this.comboBoxProd.addItem(String.valueOf(idP));
        }
    }

    public void llenaComboVend() {
        List<Integer> arr = ferrD.listaVendId();
        for (int idVend : arr) {
            this.comboBoxVend.addItem(String.valueOf(idVend));
        }
    }

    public int generaNumNot() {
        int num = (int) (Math.random() * 1000);
        String uno = "2" + num;
        int numF = Integer.parseInt(uno);
        return numF;
    }

    public int generaNumVent() {
        int num = (int) (Math.random() * 1000);
        String uno = "3" + num;
        int numF = Integer.parseInt(uno);
        return numF;
    }

    public int generaIdPV() {
        int num = (int) (Math.random() * 1000);
        String uno = "4" + num;
        int numF = Integer.parseInt(uno);
        return numF;
    }

    public double calcDesc(double total, double descuento) {
        double desc;
        desc = total * (descuento / 100);
        return desc;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnNota().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarN;
    private javax.swing.JCheckBox cbDescuento;
    private javax.swing.JComboBox<String> comboBoxProd;
    private javax.swing.JComboBox<String> comboBoxVend;
    private javax.swing.JLabel etqCantP;
    private javax.swing.JLabel etqCantP1;
    private javax.swing.JLabel etqCveVend;
    private javax.swing.JLabel etqDetV;
    private javax.swing.JLabel etqDetV1;
    private javax.swing.JLabel etqFactura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPanel panelGis;
    private javax.swing.JTextArea txtAVta;
    private javax.swing.JTextField txtCantP;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextArea txtDteVn;
    // End of variables declaration//GEN-END:variables
}
